---
- name: Create New User "{{ username }}"
  hosts: all
  remote_user: ansible
  become: false
  gather_facts: false
  vars:
# Define your username and password here that you want to create on target hosts.
    username: newuser
    userpass: user_password
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        groups: root
        append: yes

    - name: Deploy SSH Public Key to user "{{ username }}"
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ pubkey }}"
